### ISSUE TITLE
W3C Reserved Words 

### ISSUE THREAD

**Issue by espinr** [w3c/translation-glossaries#2]
Suggestion for the glossary: Reserved [process](https://www.w3.org/2019/Process-20190301/)-related terms should be translated and capitalization preserved. 
This includes:
* Type of working group: Working Group, Interest Group, Business Group, Community Group, Task Force, etc.
* W3C bodies: Members, Team, Advisory Board, Advisory Committee, Technical Architecture Group
* Technical Specifications: Working Group Note, Interest Group Note, Working Draft, First Public Working Draft, Recommendation, Proposed Recommendation, Candidate Recommendation…

**Comment by slhenry** [comment]
Thanks! Added to https://github.com/w3c/translation-glossaries/blob/master/general.md
