### ISSUE TITLE
French phrase needed

### ISSUE THREAD

**Issue by shawna-slh** [w3c/translation-glossaries#20]
Hi @wende2003 @vmmiller

We need the French translation of this phrase:
"This video is available with more accessibility features:"

You can see it in context under the videos starting here: https://deploy-preview-31--wai-eval-overview.netlify.app/test-evaluate/fr#initial

Thanks!

**Comment by vmmiller** [comment]
@shawna-slh - Here is one suggestion:

Cette vidéo est disponible avec plus de fonctionnalités d'accessibilité:

**Comment by remibetin** [comment]
> @shawna-slh - Here is one suggestion:
> 
> Cette vidéo est disponible avec plus de fonctionnalités d'accessibilité:

I concur, with a space before the colon 👍

**Comment by wende2003** [comment]
Good translation. I agree with Remi, add space before the colon
Cette vidéo est disponible avec plus de fonctionnalités d'accessibilité :

See french example about spacing & colon - https://grammaire.reverso.net/les-deux-points/

**Comment by wende2003** [comment]
Testing

**Comment by shawna-slh** [comment]
Thanks! Updated in https://github.com/w3c/wai-website-data/blob/master/translations.yml and https://deploy-preview-33--wai-eval-overview.netlify.app/test-evaluate/fr#initial
