### ISSUE TITLE
[es] "Summary" box heading translation

### ISSUE THREAD

**Issue by slhenry** [w3c/translation-glossaries#3]
Hi @rumoroso and @cmunch

For the Summary box at the top of most WAI pages:

* In a few pages it is a condensed version of the main content or the key points that we want readers to get right away, e.g., in:
  * https://www.w3.org/WAI/standards-guidelines/mobile/
  * https://www.w3.org/WAI/fundamentals/accessibility-intro/
* In most pages it is "This page tells you..."-type presentation, e.g., in:
  * https://www.w3.org/WAI/fundamentals/accessibility-principles/
  * https://www.w3.org/WAI/standards-guidelines/

Would you confer on what you think is the best Spanish translation of "Summary" for these boxes. Then we can:
* add it to https://github.com/w3c/translation-glossaries/blob/master/Castellano-Spanish.md
* update these pages as needed:
       * https://www.w3.org/WAI/fundamentals/accessibility-principles/es
       * https://www.w3.org/WAI/standards-guidelines/es
       * https://www.w3.org/WAI/standards-guidelines/mobile/es
       * and others in-progress

Thank you!

**Comment by cmunch** [comment]
I have been translating "Summary" as "Resumen", but I am fine to change that if there's a different proposal. What do you say, @rumoroso?

**Comment by espinr** [comment]
For me, it's OK 'resumen' as well. Thanks, Carlos.

**Comment by rumoroso** [comment]
+1 for "resumen" as well ;)

**Comment by slhenry** [comment]
Thank you @espinr @rumoroso @cmunch

* [x] added to [glossary](https://github.com/w3c/translation-glossaries/blob/master/Castellano-Spanish.md#summary-box-heading)
* [x] updated in [principles page](https://github.com/w3c/wai-accessibility-principles/commit/6f8198469f2db85148ffb6e674064af68bc99038#diff-0a873634125474fc15e367d405a9cc61)
* [x] updated in [mobile page](https://github.com/w3c/wai-mobile/commit/5326facc2ba1508bc6781cc5562acb40a2e579ca)
* [ ] update as needed in other translations in progress...
