### ISSUE TITLE
Spanish - FAQ or PMF

### ISSUE THREAD

**Issue by cmuncharaz** [w3c/translation-glossaries#7]
Here's a question for Spanish translators: how should we translate "FAQ" in the Spanish documents? We can find this word in different documents, linking to the FAQs.

Should we leave it as it is because this is a well known abbreviation or should we translate it? If we are to translate it, what expression should we pick?

- PMF (Preguntas más frecuentes)
- P+F
- Other?

**Comment by espinr** [comment]
FAQ or 'preguntas frecuentes'. Fundeu's [tweet](https://twitter.com/Fundeu/status/170465998686793728) recommending the term.
